version: '3'
services:
    app:
        build:
            context: .
            dockerfile: Dockerfile
        expose:
            -  '9000'
        restart: unless-stopped
        tty: true
        environment:
            working_dir: /var/www
        volumes:
            - ./:/var/www
            - ./php/local.ini:/usr/local/erc/php/conf.d/local.ini
        networks:
            - app-network
        depends_on:
            - db
    webserver:
        image: nginx
        restart: unless-stopped
        tty: true
        ports:
            - '80:80'
            - '443:443'
            - '5173:5173'
        volumes:
            - ./nginx/conf.d:/etc/nginx/conf.d
            - ./:/var/www
            - ./nginx/log/:/var/log/nginx
        networks:
            - app-network
        depends_on:
            - app
            - centrifugo
    db:
        image: mysql
        restart: unless-stopped
        ports:
            - '3306:3306'
        environment:
            MYSQL_ROOT_PASSWORD: '${DB_ROOT_PASSWORD}'
            MYSQL_DATABASE: '${DB_DATABASE}'
            MYSQL_USER: '${DB_USERNAME}'
            MYSQL_PASSWORD: '${DB_PASSWORD}'
        volumes:
            - mysql_data:/var/lib/mysql
            - ./mysql/my.cnf:/etc/my.cnf
        networks:
            - app-network
    mailhog:
        image: 'mailhog/mailhog:latest'
        restart: unless-stopped
        ports:
            - '8025:8025'
        networks:
            - app-network
    centrifugo:
        container_name: centrifugo
        image: centrifugo/centrifugo:v4
        volumes:
            - ./centrifugo/config.json:/centrifugo/config.json
        command: centrifugo -c config.json
        ports:
            - '8000:8000'
        ulimits:
            nofile:
                soft: 65535
                hard: 65535
        networks:
            - app-network
networks:
    app-network:
        driver: bridge
volumes:
    mysql_data:
        driver: local
